export default {
  displayName: 'lineup',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  coverageDirectory: '../../coverage/apps/lineup',
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/test-setup.ts',
    '!src/main.ts',
    '!src/main.server.ts',
    '!src/server.ts',
    '!src/app/app.config.ts',
    '!src/app/app.config.server.ts',
    '!src/app/app.routes.server.ts',
    '!src/**/*.routes.ts',
    '!src/**/index.ts',
    '!src/testing/**',
    '!src/app/features/business/views/catalog-download-page/catalog-download-page.ts',
    '!src/app/features/business/views/business-page/business-page.ts',
    '!src/app/features/business/views/catalog-page/catalog-page.ts',
    '!src/app/features/business/views/product-page/product-page.ts',
    '!src/app/core/services/google-auth.service.ts',
    '!src/app/features/control-panel/views/statistics-page/statistics-page.ts',
    '!src/app/features/control-panel/views/create-catalog-page/create-catalog-page.ts',
    '!src/app/features/control-panel/views/create-product-page/create-product-page.ts',
    '!src/app/features/control-panel/views/create-discount-page/create-discount-page.ts',
    '!src/app/features/control-panel/views/register-sale-page/register-sale-page.ts',
    '!src/app/features/control-panel/views/product-panel-page/product-panel-page.ts',
    '!src/app/features/control-panel/views/edit-business-page/edit-business-page.ts',
    '!src/app/features/control-panel/views/catalog-panel-page/catalog-panel-page.ts',
    '!src/app/features/control-panel/views/update-product-sku-page/update-product-sku-page.ts',
    '!src/app/features/control-panel/views/business-hours-page/business-hours-page.ts',
    '!src/app/features/control-panel/views/business-settings-page/business-settings-page.ts',
    '!src/app/features/control-panel/views/discount-page/discount-page.ts',
    '!src/app/features/home/views/home-page/home-page.ts',
    '!src/app/features/user/views/profile-page/profile-page.ts',
  ],
  transform: {
    '^.+\\.(ts|mjs|js|html)$': [
      'jest-preset-angular',
      {
        tsconfig: '<rootDir>/tsconfig.spec.json',
        stringifyContentPathRegex: '\\.(html|svg)$',
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment',
  ],
};
