export enum ColorValueEnum {
  BLACK = 'black',
  WHITE = 'white',
  RED = 'red',
  GREEN = 'green',
  BLUE = 'blue',
  YELLOW = 'yellow',
  ORANGE = 'orange',
  PURPLE = 'purple',
  PINK = 'pink',
  GRAY = 'gray',
  BROWN = 'brown',
  BEIGE = 'beige',
  LIGHT_BLUE = 'lightblue',
  LIGHT_GREEN = 'lightgreen',
  LIGHT_PINK = 'lightpink',
  LIGHT_YELLOW = 'lightyellow',
  LAVENDER = 'lavender',
  MINT = 'mintcream',
  PEACH = 'peachpuff',
  CORAL = 'lightcoral',
  TURQUOISE = 'turquoise',
}

