export enum ColorNameEnum {
  BLACK = 'colors.black',
  WHITE = 'colors.white',
  RED = 'colors.red',
  GREEN = 'colors.green',
  BLUE = 'colors.blue',
  YELLOW = 'colors.yellow',
  ORANGE = 'colors.orange',
  PURPLE = 'colors.purple',
  PINK = 'colors.pink',
  GRAY = 'colors.gray',
  BROWN = 'colors.brown',
  BEIGE = 'colors.beige',
  LIGHT_BLUE = 'colors.light_blue',
  LIGHT_GREEN = 'colors.light_green',
  LIGHT_PINK = 'colors.light_pink',
  LIGHT_YELLOW = 'colors.light_yellow',
  LAVENDER = 'colors.lavender',
  MINT = 'colors.mint',
  PEACH = 'colors.peach',
  CORAL = 'colors.coral',
  TURQUOISE = 'colors.turquoise',
}

