export enum StatusEnum {
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
  DENIED = 'DENIED',
  FAILED = 'FAILED',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED'
}
